name: Build PR

on: pull_request

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm i
          npm run build