name: CI

push:
  branches:
    - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm i
          npm run build

      # Publish when running on main
      - name: Publish Website
        if: startsWith(github.ref, 'refs/heads/main')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/